services:
  tailguard:
    image: ghcr.io/juhovh/tailguard:latest
    build: .
    volumes:
      - ./config:/etc/wireguard
      - ./state:/tailguard/state
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - ip6net
    ports:
      - "41641:41641/udp"
    restart: unless-stopped

networks:
  ip6net:
    enable_ipv6: true
